include:
  - local: '/ci/templates/cache.gitlab-ci.yml'

.gradle-job:
  before_script:
    - source /load-env.sh
  image: ${CI_REGISTRY}/android/shared/docker-android:1.0.3-github-ssh-key-snapshot
  variables:
    GRADLE_USER_HOME: '$CI_PROJECT_DIR/.gradle'
  tags:
    - xlarge-k8s
  cache:
    - !reference [.gradle-cache, cache]

.ruby-job:
  image: ${CI_REGISTRY}/android/shared/docker-android:1.0.3-github-ssh-key-snapshot
  variables:
    BUNDLE_GEM_PATH: 'vendor/ruby'
  cache:
    - !reference [.ruby-cache, cache]
  before_script:
    - bundle config set path ${BUNDLE_GEM_PATH}
    - bundle config set without 'production'
    - bundle install

.script-job:
  image: ${CI_REGISTRY}/android/shared/docker-android:1.0.3-github-ssh-key-snapshot
  cache: []
