.gradle-job:
  before_script:
    - source /load-env.sh
  tags:
    - xlarge-k8s
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .gradle/caches
      - .gradle/configuration-cache

.ruby-job:
  variables:
    BUNDLE_GEM_PATH: 'vendor/ruby'
  cache:
    - key:
        prefix: ruby-cache
        files:
          - Gemfile.lock
      paths:
        - ${BUNDLE_GEM_PATH}
      policy: pull-push
  before_script:
    - bundle config set path ${BUNDLE_GEM_PATH}
    - bundle config set without 'production'
    - bundle install

.script-job:
  cache: []
